export const dataScreen9 = [
Fundada em 1998 a Pilar Comercial e Serviços iniciou suas atividades fabricando e revendendo papel para outras empresas do setor de embalagem de papel.
Com o intuito de ampliar as vendas, decidimos iniciar uma linha de produtos comerciais, utilizando como base nossa matéria prima industrial.
A família Pilar tem longa tradição no mercado papeleiro. A primeira empresa de grupo foi montada em 1960 pelo patriarca da família, Sr. Adhemur Pilar, que depois colocou seus filhos Fernando Pilar e Marcello como sócios
Aproveitando a experiência do pai, a empresa começou como representação de papel. No final dos anos 70, assumiu a fábrica de papel CIBRAP - Cia. Brasileira de Papel, dirigida pelos irmãos até o final da década de 80, quando foi vendida para o grupo KLABIN. Ambos continuaram trabalhando no segmento, atuando na área comercial e industrial de empresas como KLABIN, VOTORANTIM E CELULOSE IRANI.
Desde 2002, a matriz da empresa está instalada em área própria, entre o Rodoanel e a Regis Bittencourt, na cidade de Embu das Artes. E hoje já ampliou sua area para mais 2 novas unidades mais uma em Embú e outra em São Lourenço da Serra. Perfazendo uma área de mais de 24 mil metros de area contruida.
As principais linhas de atuação são os mercados industriais e gráficos, porém utilizando como base nossos papéis hoje trabalhados acrescentamos a nossa linha produtos descartáveis, escolares, embalagens e produtos para proteção.
Afim de proporcionar um melhor atendimento, com maior rapidez nas entregas, nos últimos anos algumas filiais pelo Brasil foram abertas. (Hoje contando com mais 9 unidades e uma fábrica de papel em Sengês PR)
A idéia de unir vários produtos fabricados, tendo como base a matéria prima papel, é a que nos move e incentiva a continuar crescendo
];